version = 1

test_patterns = [
    "__tests__/*.test.ts",
    "__tests__/**"
]

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
dialect = "typescript"
environment = [
  "nodejs",
  "browser"
]

[[transformers]]
name = "prettier"
enabled = true